## !!!!!!用于docker-compose部署并启动官方镜像!!!!!!
## !!!!!!挂载配置的形式启动，方便修改配置!!!!!!!!!!!!
## !!!!!!需要依赖项目配置文件!!!!!!!!!!!!!!!!!!!!!!

version: '3'
services:

  #http模式启动api服务
  api-http:
    profiles: ['http']
    image: iamtsm/tl-rtc-file-api
    container_name: api
    env_file:
      - tlrtcfile.env
    environment:
      - tl_rtc_file_env_mode=http
      - tl_rtc_file_db_open=true
    command: 
      - tlapi
    ports:
      - 9092:9092
    links:
      - mysql
    depends_on:
      - mysql
      - coturn
    volumes:
      - tlrtcfile.env:/tlrtcfile/tlrtcfile.env

  #https模式启动api服务
  api-https:
    profiles: ['https']
    image: iamtsm/tl-rtc-file-api
    container_name: api
    env_file:
      - tlrtcfile.env
    environment:
      - tl_rtc_file_env_mode=https
      - tl_rtc_file_db_open=true
    command: 
      - tlapi
    ports:
      - 9092:9092
    links:
      - mysql
    depends_on:
      - mysql
      - coturn
    volumes:
      - tlrtcfile.env:/tlrtcfile/tlrtcfile.env

  #http模式启动socket服务
  socket-http:
    profiles: ['http']
    image: iamtsm/tl-rtc-file-socket
    container_name: socket
    command: 
      - tlsocket
    env_file:
      - tlrtcfile.env
    environment:
      - tl_rtc_file_env_mode=http
      - tl_rtc_file_db_open=true
    ports:
      - 8444:8444
    links:
      - mysql
    depends_on:
      - mysql
      - coturn
    volumes:
      - tlrtcfile.env:/tlrtcfile/tlrtcfile.env

  #https模式启动socket服务
  socket-https:
    profiles: ['https']
    image: iamtsm/tl-rtc-file-socket
    container_name: socket
    command: 
      - tlsocket
    env_file:
      - tlrtcfile.env
    environment:
      - tl_rtc_file_env_mode=https
      - tl_rtc_file_db_open=true
    ports:
      - 8444:8444
    links:
      - mysql
    depends_on:
      - mysql
      - coturn
    volumes:
      - tlrtcfile.env:/tlrtcfile/tlrtcfile.env

  #mysql服务
  mysql:
    profiles: ['http','https']
    image: iamtsm/tl-rtc-file-mysql
    container_name: mysql
    restart: always
    environment:
      #设置root密码
      - MYSQL_ROOT_PASSWORD=tlrtcfile
      #设置数据库
      - MYSQL_DATABASE=webchat
      #设置用户
      - MYSQL_USER=tlrtcfile
      #设置用户密码
      - MYSQL_PASSWORD=tlrtcfile
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data/db:/var/lib/mysql
      - ./docker/mysql/data/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data/log:/var/log/mysql
      - ./docker/mysql/data/init.sql:/docker-entrypoint-initdb.d/init.sql

  #coturn服务
  coturn:
    profiles: ['http','https']
    image: iamtsm/tl-rtc-file-coturn
    container_name: coturn
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
    volumes:
      - ./docker/coturn/turnserver-with-secret-user.conf:/etc/turnserver.conf